# Generated by Django 5.0.2 on 2024-02-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(max_length=50)),
                ('Team_Password', models.CharField(max_length=50)),
                ('Team_Photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('Team_Status', models.IntegerField(default='0')),
            ],
        ),
    ]
