# Generated by Django 5.0.2 on 2024-02-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Player_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tbl_team',
            name='Team_Photo',
            field=models.FileField(upload_to='Assets/Team_Photo/'),
        ),
    ]
